export { CategoriesSection } from './Section/CategoriesSection'
export { MainDescriptionSection } from './Section/MainDescriptionSection'
export { ItemPresentation } from './Card/ItemCategory'
export { ItemShortCard } from './Card/ItemShortCard'
export { InnerNav } from './Nav/InnerNav'
export { MainNav } from './Nav/MainNav'
export { FooterNav } from './Nav/FooterNav'
export { CartModal } from './Card/CartModal'
